export const INVOICE_DATA = {
  air_ticket: [
    { code: 'ticketNumber', label: '电子客票号码' },
    { code: 'ck', label: '验证码' },
    { code: 'name', label: '姓名' },
    { code: 'seatNum', label: '航班号' },
    { code: 'startingStation', label: '始发站' },
    { code: 'destinationStation', label: '目的站' },
    { code: 'date', label: '日期' },
    { code: 'carrier', label: '承运人' },
    { code: 'clasz', label: '座位等级' },
    { code: 'fuelSurcharge', label: '燃油附加费' },
    { code: 'otherTax', label: '其他税费' },
    { code: 'ticketRates', label: '合计金额' },
  ],
  quota_invoice: [
    { code: 'code', label: '发票代码' },
    { code: 'number', label: '发票号码' },
    { code: 'province', label: '省' },
    { code: 'city', label: '市' },
    { code: 'location', label: '发票所在地' },
    { code: 'date', label: '日期' },
    { code: 'totalFee', label: '发票金额' },
  ],
  taxi_receipt: [
    { code: 'invoiceCode', label: '发票代码' },
    { code: 'invoiceNum', label: '发票号码' },
    { code: 'location', label: '开票城市' },
    { code: 'distance', label: '里程' },
    { code: 'date', label: '日期' },
    { code: 'fare', label: '金额' },
  ],
  train_ticket: [
    { code: 'ticketNum', label: '车票号' },
    { code: 'trainNum', label: '车次' },
    { code: 'seatCategory', label: '座席' },
    { code: 'name', label: '姓名' },
    { code: 'startingStation', label: '出发城市' },
    { code: 'destinationStation', label: '到达城市' },
    { code: 'date', label: '日期' },
    { code: 'ticketRates', label: '车票金额' },
  ],
  vat_invoice: [
    { code: 'serviceType', label: '费用类型' },
    { code: 'code', label: '发票代码' },
    { code: 'number', label: '发票号码' },
    { code: 'checkCode', label: '校验码' },
    { code: 'date', label: '开票日期' },
    { code: 'purchaserName', label: '购买方名称' },
    { code: 'purchaserRegisterNum', label: '购方纳税人识别号' },
    { code: 'sellerName', label: '销售方名称' },
    { code: 'sellerRegisterNum', label: '销售方识别号' },
    // { code: 'commodityVehicleType.commodityPlateNum', label: '车牌号' },
    // { code: 'commodityVehicleType.commodityStartDate', label: '通行日期起' },
    // { code: 'commodityVehicleType.commodityEndDate', label: '通行日期止' },
    { code: 'commodityPlateNum', label: '车牌号' },
    { code: 'commodityStartDate', label: '通行日期起' },
    { code: 'commodityEndDate', label: '通行日期止' },
    { code: 'totalFee', label: '不含税金额' },
    { code: 'amountInFiguers', label: '票面金额' },
  ],
  social_group_dues: [
    { code: 'invoiceCode', label: '票据代码' },
    { code: 'invoiceNum', label: '票据号码' },
    { code: 'checkCode', label: '校验码' },
    { code: 'invoiceDate', label: '开票日期' },
    { code: 'payerRegisterNum', label: '交款人统一社会信用代码' },
    { code: 'payerName', label: '交款人' },
    { code: 'amount', label: '金额' },
  ],
  non_tax_income: [
    { code: 'invoiceCode', label: '票据代码' },
    { code: 'invoiceNum', label: '票据号码' },
    { code: 'checkCode', label: '校验码' },
    { code: 'invoiceDate', label: '填制日期' },
    { code: 'paymentCode', label: '缴款码' },
    { code: 'payerName', label: '付款人' },
    { code: 'payeeName', label: '收款人' },
    { code: 'amount', label: '金额' },
  ],
  tax_payment_certificate: [
    { code: 'number', label: '发票号码' },
    { code: 'purchaserRegisterNum', label: '纳税人识别号' },
    { code: 'purchaserName', label: '纳税人名称' },
    { code: 'voucherNo', label: '原凭证号' },
    { code: 'sellerName', label: '税务机关' },
    { code: 'issuedDate', label: '日期' },
    { code: 'amount', label: '金额' },
  ]
};

export const INVOICE_TYPE = {
  vat_invoice: '增值税发票',
  quota_invoice: '定额发票',
  taxi_receipt: '出租车发票',
  train_ticket: '火车票',
  air_ticket: '飞机行程单',
  social_group_dues: '社会团体会费财政票据',
  non_tax_income: '非税收入一般缴款书',
  tax_payment_certificate: "税收完税证明",
  // bus_ticket: '汽车票',
  // printed_invoice: '机打发票',
  // toll_invoice: '过路过桥费发票',
  // ferry_ticket: '船票',
  // taxi_online_ticket: '网约车行程单',
  // limit_invoice: '限额发票',
  // shopping_receipt: '购物小票',
  // pos_invoice: 'pos小票',
  // motor_vehicle_invoice: '机动车销售发票',
  // roll_normal_invoice: '卷票',
  // used_vehicle_invoice: '二手车发票',
  // others: '其他',
};
